//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_Number { get; set; }
        public Nullable<int> Client_Code { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<int> Vehicle_Code { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
