//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifications
    {
        public int Vehicle_Code { get; set; }
        public string Model { get; set; }
        public Nullable<int> Stamp_Code { get; set; }
        public string Year_Of_Release { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Engine_Number { get; set; }
        public string Body_Type { get; set; }
        public Nullable<int> Engine_Capacity { get; set; }
        public string VIN { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Stamps Stamps { get; set; }
    }
}
